import { Link, useParams } from 'react-router-dom'
import { usePublicData,usePageTitle } from '../hooks/usePublicData'
import { historicalCollectionsService as service } from '../../services/historicalCollectionsService'
import HistoricalCollectionCard, { HistoricalEditorialCover } from '../components/HistoricalCollectionCard'
import { PublicEmpty,PublicError,PublicLoading } from '../components/PublicStates'
import { historicalSectionCovers,pennantGroupCovers } from '../config/historicalCollectionIdentity'

const names:Record<string,string>={brasil:'Brasil',italy:'Itália',other:'Outros'}
const routes:Record<string,string>={pennants:'flamulas',flags:'bandeiras',memorabilia:'memorabilia'}
const descriptions:Record<string,string>={pennants:'Flâmulas históricas preservadas em seus três grupos originais.',flags:'Bandeiras, faixas e objetos físicos da coleção.',memorabilia:'Objetos e lembranças históricas ligados ao futebol.'}
function State({loading,error,empty=false}:{loading:boolean;error:boolean;empty?:boolean}){if(loading)return <PublicLoading/>;if(error)return <PublicError/>;if(empty)return <PublicEmpty/>;return null}

export function PublicHistoricalCollectionsHome(){usePageTitle('Coleções');const{data,loading,error}=usePublicData(()=>service.summary(),[]);return <section className="public-section historical-collections-home"><header className="public-page-header"><p className="public-kicker">Acervo complementar</p><h1>Coleções</h1><p>Flâmulas, bandeiras e memorabilia preservadas como domínios históricos próprios.</p></header><State loading={loading} error={error}/>{data&&<div className="public-card-grid historical-section-grid">{data.sections.map(section=>{const cover=historicalSectionCovers[section.section];return <HistoricalCollectionCard key={section.section} title={section.title} description={section.description} mediaUrl={cover.src} imageAlt={cover.alt} editorialCover meta={`${section.itemsCount} itens`} to={`/site/colecoes/${routes[section.section]}`}/>})}</div>}</section>}

export function PublicPennantsHome(){usePageTitle('Flâmulas');const{data,loading,error}=usePublicData(()=>service.section('pennants'),[]);return <section className="public-section historical-pennants-home"><header className="public-page-header"><p className="public-kicker">Coleções</p><h1>Flâmulas</h1><p>{descriptions.pennants}</p></header><State loading={loading} error={error}/>{data&&<div className="historical-group-grid">{(data.groups??[]).map(group=>{const cover=pennantGroupCovers[group.groupKey];return <Link className="historical-group-card" key={group.groupKey} to={`/site/colecoes/flamulas/${group.groupKey==='italy'?'italia':group.groupKey==='other'?'outros':'brasil'}`}><div className="historical-group-media"><HistoricalEditorialCover src={cover.src} alt={cover.alt} title={names[group.groupKey]}/></div><div className="historical-group-copy"><span>{group.count} itens</span><h2>{names[group.groupKey]}</h2><b>Explorar grupo →</b></div></Link>})}</div>}</section>}

export function PublicHistoricalItemsPage({section}:{section:'pennants'|'flags'|'memorabilia'}){const params=useParams();const group=section==='pennants'?(params.group==='italia'?'italy':params.group==='outros'?'other':'brasil'):undefined;const{data,loading,error}=usePublicData(()=>service.items(section,{group,limit:100,offset:0}),[section,group]);const title=section==='pennants'?`Flâmulas — ${names[group!]}`:section==='flags'?'Bandeiras':'Memorabilia';usePageTitle(title);return <section className="public-section"><header className="public-page-header"><p className="public-kicker">Coleções históricas</p><h1>{title}</h1><p>{descriptions[section]}</p></header><State loading={loading} error={error} empty={!!data&&!data.total}/>{data&&<div className="public-card-grid historical-items-grid">{data.items.map(item=><HistoricalCollectionCard key={item.slug} title={item.title||'Item histórico sem legenda'} description={item.description} mediaUrl={item.mediaUrl} to={section==='pennants'?undefined:item.route} meta={item.category?item.category.replace('bracadeiras','braçadeiras'):item.status==='review_required'?'Legenda em revisão':undefined}/>)}</div>}</section>}

export function PublicHistoricalItemPage({section}:{section:'flags'|'memorabilia'}){const{slug=''}=useParams();const{data,loading,error}=usePublicData(()=>service.item(section,slug),[section,slug]);usePageTitle(data?.title||'Item histórico');return <section className="public-section"><State loading={loading} error={error}/>{data&&<div className="public-item-detail historical-item-detail"><div>{data.mediaUrl?<img className="public-media public-gallery-main" src={data.mediaUrl} alt={data.title||'Item histórico'}/>:<div className="public-media public-media-fallback"><span>FC</span></div>}</div><div><p className="public-kicker">{section==='flags'?'Bandeiras':'Memorabilia'}</p><h1>{data.title||'Item histórico sem legenda'}</h1>{data.description&&<p className="public-description">{data.description}</p>}{data.category&&<dl className="public-facts"><div><dt>Categoria</dt><dd>{data.category.replace('bracadeiras','braçadeiras')}</dd></div></dl>}<Link className="public-record-link" to={`/site/colecoes/${section==='flags'?'bandeiras':'memorabilia'}`}>← Voltar à coleção</Link></div></div>}</section>}
