import { useMemo,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import PublicBreadcrumbs from '../components/PublicBreadcrumbs'
import { PublicCountryCard,PublicItemCard,PublicTeamCard } from '../components/PublicCards'
import PublicMediaImage from '../components/PublicMediaImage'
import PublicHeroMedia from '../components/PublicHeroMedia'
import ChicaoMemorialSection from '../components/ChicaoMemorialSection'
import { PublicTeamLogo } from '../components/PublicIdentityMedia'
import { publicSiteConfig } from '../config/publicSiteConfig'
import { PublicEmpty,PublicError,PublicLoading } from '../components/PublicStates'
import { usePageTitle,usePublicData } from '../hooks/usePublicData'
import { publicSiteService as api } from '../services/publicSiteService'
import { teamDisplayName } from '../utils/teamDisplayName'
import { countryDisplayName } from '../utils/countryDisplayName'

const pretty=(x:string)=>x.replaceAll('_',' ')
const Gate=({x,children}:{x:{loading:boolean;error:boolean;data:unknown};children:React.ReactNode})=>x.loading?<PublicLoading/>:x.error?<PublicError/>:!x.data?<PublicEmpty/>:<>{children}</>
const Grid=({children}:{children:React.ReactNode})=><div className="public-card-grid">{children}</div>
const FeaturedTeamGrid=({children}:{children:React.ReactNode})=><div className="public-card-grid public-featured-team-grid">{children}</div>
const Heading=({over,title,copy}:{over:string;title:string;copy?:string})=><header className="public-page-header"><p className="public-kicker">{over}</p><h1>{pretty(title)}</h1>{copy&&<p>{copy}</p>}</header>
const Section=({title,children,link}:{title:string;children:React.ReactNode;link?:string})=><section className={`public-section${title==='Últimas inclusões'?' public-latest-section':title==='Países e regiões'?' public-countries-section':''}`}><div className="public-section-heading"><h2>{title==='Países e regiões'?'Explore o acervo':title}</h2>{link&&<Link to={link}>Ver todos →</Link>}</div>{children}</section>

export function PublicHomeEditorialPage(){usePageTitle('Football Collection');const x=usePublicData(async()=>{const[summary,countries,latest,teams]=await Promise.all([api.getSummary(),api.getCountries(),api.latest(),api.getTeams({limit:100})]);return{summary,countries:countries.items,latest:latest.items,teams:teams.items.sort((a,b)=>b.itemsCount-a.itemsCount).slice(0,8)}},[]);return <Gate x={x}><>{x.data&&<><section className="public-hero"><PublicHeroMedia media={publicSiteConfig.heroMedia}/></section><section className="public-numbers">{[['Equipes',x.data.summary.teams],['Coleções',x.data.summary.collections],['Itens',x.data.summary.items],['Imagens',x.data.summary.mediaRelations]].map(([a,b])=><div key={String(a)}><strong>{Number(b).toLocaleString('pt-BR')}</strong><span>{a}</span></div>)}</section><Section title="Últimas inclusões" link="/site/ultimas"><Grid>{x.data.latest.slice(0,8).map(i=><PublicItemCard key={i.publicRoute} item={i}/>)}</Grid></Section><Section title="Países e regiões" link="/site/paises"><Grid>{x.data.countries.map(i=><PublicCountryCard key={i.slug} item={i} editorial/>)}</Grid></Section><Section title="Equipes em destaque" link="/site/equipes"><FeaturedTeamGrid>{x.data.teams.map(i=><PublicTeamCard key={`${i.countrySlug}-${i.slug}`} item={i} featured/>)}</FeaturedTeamGrid></Section><ChicaoMemorialSection/></>}</></Gate>}

export function PublicTeamEditorialPage(){const{countrySlug='',teamSlug=''}=useParams();const x=usePublicData(async()=>{const[detail,items]=await Promise.all([api.getTeam(countrySlug,teamSlug),api.getItems({country:countrySlug,team:teamSlug,limit:100})]);return{detail,items:items.items}},[countrySlug,teamSlug]),displayName=x.data?teamDisplayName(x.data.detail.team):'Equipe',countryName=countryDisplayName(countrySlug);usePageTitle(displayName);return <Gate x={x}><>{x.data&&<><PublicBreadcrumbs items={[{label:countryName,to:`/site/paises/${countrySlug}`},{label:displayName}]}/><div className="public-detail-hero"><div><Heading over={countryName} title={displayName}/><p>{x.data.detail.team.itemsCount} itens · {x.data.detail.team.imagesCount} imagens</p></div><PublicTeamLogo media={x.data.detail.team.logoMedia} name={displayName}/></div><Section title="Camisas por ano ou temporada"><Grid>{x.data.items.map(i=><PublicItemCard key={i.publicRoute} item={i}/>)}</Grid></Section></>}</></Gate>}

export function PublicCollectionEditorialPage(){const{countrySlug='',teamSlug='',collectionSlug=''}=useParams(),displayName=teamDisplayName(teamSlug,countrySlug);const x=usePublicData(()=>api.getCollection(countrySlug,teamSlug,collectionSlug),[countrySlug,teamSlug,collectionSlug]);usePageTitle(`Camisas de ${displayName}`);return <Gate x={x}><>{x.data&&<><PublicBreadcrumbs items={[{label:countryDisplayName(countrySlug),to:`/site/paises/${countrySlug}`},{label:displayName,to:`/site/paises/${countrySlug}/equipes/${teamSlug}`},{label:'Camisas'}]}/><Heading over={displayName} title="Camisas da equipe"/><Grid>{x.data.items.items.map(i=><PublicItemCard key={i.publicRoute} item={i}/>)}</Grid></>}</></Gate>}

export function PublicItemEditorialPage(){const{countrySlug='',teamSlug='',collectionSlug,itemSlug=''}=useParams(),displayName=teamDisplayName(teamSlug,countrySlug);const x=usePublicData(()=>collectionSlug?api.getItemWithCollection(countrySlug,teamSlug,collectionSlug,itemSlug):api.getItemWithoutCollection(countrySlug,teamSlug,itemSlug),[countrySlug,teamSlug,collectionSlug,itemSlug]);usePageTitle(x.data?.seasonLabel||x.data?.title||'Item');const[selected,setSelected]=useState<string|null>(null),media=useMemo(()=>x.data?.media?.filter(m=>m.mediaUrl)||[],[x.data]),active=media.find(m=>m.mediaKey===selected)||media[0]||x.data?.primaryMedia,hasMedia=Boolean(active?.mediaUrl);return <Gate x={x}><>{x.data&&<><PublicBreadcrumbs items={[{label:countryDisplayName(countrySlug),to:`/site/paises/${countrySlug}`},{label:displayName,to:`/site/paises/${countrySlug}/equipes/${teamSlug}`},{label:x.data.seasonLabel||x.data.title}]}/><article className="public-item-detail"><div className="public-gallery"><PublicMediaImage media={active} alt={x.data.title} eager className="public-gallery-main"/>{!hasMedia&&<p className="public-media-notice" role="status">Registro histórico preservado sem mídia disponível.</p>}{media.length>1&&<div className="public-gallery-thumbs">{media.map((m,i)=><button key={m.mediaKey||i} className={m.mediaKey===active?.mediaKey?'active':''} aria-label={`Ver imagem ${i+1}`} onClick={()=>setSelected(m.mediaKey)}><PublicMediaImage media={m} alt={`${x.data!.title}, imagem ${i+1}`}/></button>)}</div>}</div><div><Heading over={displayName} title={x.data.seasonLabel||x.data.title}/>{x.data.competition&&<p className="public-competition">{x.data.competition}</p>}{x.data.description&&<p className="public-description">{x.data.description}</p>}<dl className="public-facts"><div><dt>País / região</dt><dd>{countryDisplayName(countrySlug)}</dd></div><div><dt>Equipe</dt><dd>{displayName}</dd></div><div><dt>Imagens</dt><dd>{x.data.imagesCount}</dd></div></dl></div></article></>}</></Gate>}

export function PublicLatestEditorialPage(){usePageTitle('Últimas inclusões');const[country,setCountry]=useState(''),countries=usePublicData(()=>api.getCountries(),[]),x=usePublicData(()=>api.latest(country),[country]);return <><Heading over="Novidades do acervo" title="Últimas inclusões" copy="Camisas recentemente incorporadas ao arquivo, apresentadas por seu ano ou título histórico."/><label className="public-latest-filter">País ou região<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">Todos</option>{countries.data?.items.map(i=><option key={i.slug} value={i.slug}>{countryDisplayName(i.slug||i.name)}</option>)}</select></label><Gate x={x}><Grid>{x.data?.items.map(i=><PublicItemCard key={i.publicRoute} item={i}/>)}</Grid></Gate></>}
