/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect,useMemo,useState } from 'react'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { PublicCollectionCard,PublicCountryCard,PublicItemCard,PublicTeamCard } from '../components/PublicCards'
import PublicBreadcrumbs from '../components/PublicBreadcrumbs'
import PublicMediaImage from '../components/PublicMediaImage'
import { PublicEmpty,PublicError,PublicLoading } from '../components/PublicStates'
import { usePageTitle,usePublicData } from '../hooks/usePublicData'
import { publicSiteService as api } from '../services/publicSiteService'
import type { SearchResult } from '../types'

const pretty=(x:string)=>x.replaceAll('_',' ')
const Header=({eyebrow,title,copy}:{eyebrow?:string;title:string;copy?:string})=><header className="public-page-header">{eyebrow&&<p className="public-kicker">{eyebrow}</p>}<h1>{pretty(title)}</h1>{copy&&<p>{copy}</p>}</header>
const Grid=({children}:{children:React.ReactNode})=><div className="public-card-grid">{children}</div>
const Gate=({loading,error,empty,children}:{loading:boolean;error:boolean;empty?:boolean;children:React.ReactNode})=>loading?<PublicLoading/>:error?<PublicError/>:empty?<PublicEmpty/>:<>{children}</>
const Pagination=({offset,total,onChange}:{offset:number;total:number;onChange:(n:number)=>void})=><nav className="public-pagination" aria-label="Paginação"><button disabled={offset===0} onClick={()=>onChange(Math.max(0,offset-24))}>Anterior</button><span>{total?`${offset+1}–${Math.min(offset+24,total)} de ${total}`:'0 resultados'}</span><button disabled={offset+24>=total} onClick={()=>onChange(offset+24)}>Próxima</button></nav>

export function PublicHomePage(){usePageTitle('Football Collection');const{data,loading,error}=usePublicData(async()=>{const[summary,countries,latest,teams]=await Promise.all([api.getSummary(),api.getCountries(),api.latest(),api.getTeams({limit:100})]);return{summary,countries:countries.items,latest:latest.items,teams:teams.items.sort((a,b)=>b.itemsCount-a.itemsCount).slice(0,8)}},[]);return <Gate loading={loading} error={error} empty={!data}><>{data&&<><section className="public-hero"><div className="public-hero-copy"><p className="public-kicker">Arquivo independente de futebol</p><h1>Football<br/>Collection</h1><p>Uma coleção de camisas e histórias do futebol, preservada para ser explorada.</p><Link className="public-cta" to="/site/paises">Explorar o acervo <span>→</span></Link></div><PublicMediaImage media={data.latest[0]?.primaryMedia} alt={data.latest[0]?.name||'Football Collection'} eager className="public-hero-image"/></section><section className="public-numbers" aria-label="Resumo da coleção">{[['Equipes',data.summary.teams],['Coleções',data.summary.collections],['Itens',data.summary.items],['Imagens',data.summary.mediaRelations]].map(([x,n])=><div key={String(x)}><strong>{Number(n).toLocaleString('pt-BR')}</strong><span>{x}</span></div>)}</section><Section title="Últimas inclusões" link="/site/ultimas"><Grid>{data.latest.slice(0,8).map(x=><PublicCollectionCard key={`${x.countrySlug}-${x.teamSlug}-${x.slug}`} item={x}/>)}</Grid></Section><Section title="Países e regiões" link="/site/paises"><Grid>{data.countries.map(x=><PublicCountryCard key={x.slug} item={x}/>)}</Grid></Section><Section title="Equipes em destaque" link="/site/equipes"><Grid>{data.teams.map(x=><PublicTeamCard key={`${x.countrySlug}-${x.slug}`} item={x}/>)}</Grid></Section></>}</></Gate>}
function Section({title,link,children}:{title:string;link?:string;children:React.ReactNode}){return <section className="public-section"><div className="public-section-heading"><h2>{title}</h2>{link&&<Link to={link}>Ver todos →</Link>}</div>{children}</section>}

export function PublicCountriesPage(){usePageTitle('Países');const x=usePublicData(()=>api.getCountries(),[]);return <><Header eyebrow="Explore o acervo" title="Países e regiões" copy="Descubra equipes e coleções organizadas por origem."/><Gate loading={x.loading} error={x.error} empty={!x.data?.items.length}><Grid>{x.data?.items.map(i=><PublicCountryCard key={i.slug} item={i}/>)}</Grid></Gate></>}
export function PublicCountryPage(){const{countrySlug=''}=useParams();const x=usePublicData(()=>api.getCountry(countrySlug),[countrySlug]);usePageTitle(x.data?.country.name||'País');return <Gate loading={x.loading} error={x.error} empty={!x.data}><>{x.data&&<><PublicBreadcrumbs items={[{label:x.data.country.name}]}/><div className="public-detail-hero"><div><Header eyebrow="País / região" title={x.data.country.name}/><p>{x.data.summary.teams} equipes · {x.data.summary.collections} coleções · {x.data.summary.items} itens</p></div><PublicMediaImage media={x.data.country.primaryMedia} alt={x.data.country.name}/></div><Section title="Equipes"><Grid>{x.data.teams.map(i=><PublicTeamCard key={i.slug} item={i}/>)}</Grid></Section></>}</></Gate>}

export function PublicTeamsPage(){usePageTitle('Equipes');const[offset,setOffset]=useState(0),[search,setSearch]=useState(''),[country,setCountry]=useState('');const countries=usePublicData(()=>api.getCountries(),[]),teams=usePublicData(()=>api.getTeams({offset,search,country}),[offset,search,country]);return <><Header eyebrow="Clubes e seleções" title="Equipes" copy="Navegue pelas equipes representadas na coleção."/><div className="public-filters"><label>Buscar equipe<input value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></label><label>País ou região<select value={country} onChange={e=>{setCountry(e.target.value);setOffset(0)}}><option value="">Todos</option>{countries.data?.items.map(x=><option key={x.slug} value={x.slug}>{pretty(x.name)}</option>)}</select></label></div><Gate loading={teams.loading} error={teams.error} empty={!teams.data?.items.length}><Grid>{teams.data?.items.map(i=><PublicTeamCard key={`${i.countrySlug}-${i.slug}`} item={i}/>)}</Grid></Gate>{teams.data&&<Pagination offset={offset} total={teams.data.total} onChange={setOffset}/>}</>}
export function PublicTeamPage(){const{countrySlug='',teamSlug=''}=useParams();const x=usePublicData(()=>api.getTeam(countrySlug,teamSlug),[countrySlug,teamSlug]);usePageTitle(x.data?.team.name||'Equipe');return <Gate loading={x.loading} error={x.error} empty={!x.data}><>{x.data&&<><PublicBreadcrumbs items={[{label:x.data.country.name,to:`/site/paises/${countrySlug}`},{label:x.data.team.name}]}/><div className="public-detail-hero"><div><Header eyebrow={x.data.country.name} title={x.data.team.name}/><p>{x.data.team.collectionsCount} coleções · {x.data.team.itemsCount} itens · {x.data.team.imagesCount} imagens</p></div><PublicMediaImage media={x.data.team.primaryMedia} alt={x.data.team.name}/></div><Section title="Coleções"><Grid>{x.data.latestCollections.map(i=><PublicCollectionCard key={i.slug} item={i}/>)}</Grid></Section></>}</></Gate>}

export function PublicCollectionPage(){const{countrySlug='',teamSlug='',collectionSlug=''}=useParams();const x=usePublicData(()=>api.getCollection(countrySlug,teamSlug,collectionSlug),[countrySlug,teamSlug,collectionSlug]);usePageTitle(x.data?.collection.name||'Coleção');const period=x.data?.collection;return <Gate loading={x.loading} error={x.error} empty={!x.data}><>{x.data&&<><PublicBreadcrumbs items={[{label:countrySlug,to:`/site/paises/${countrySlug}`},{label:teamSlug,to:`/site/paises/${countrySlug}/equipes/${teamSlug}`},{label:x.data.collection.name}]}/><div className="public-detail-hero"><div><Header eyebrow={teamSlug} title={x.data.collection.displayPeriod||x.data.collection.name}/>{period?.inclusionYear&&<p>Incluído na coleção em {String(period.inclusionMonth).padStart(2,'0')}/{period.inclusionYear}{period.inclusionBatch?` — lote ${period.inclusionBatch}`:''}</p>}</div><PublicMediaImage media={x.data.collection.primaryMedia} alt={x.data.collection.name}/></div><Section title="Itens"><Gate loading={false} error={false} empty={!x.data.items.items.length}><Grid>{x.data.items.items.map(i=><PublicItemCard key={i.slug} item={i}/>)}</Grid></Gate></Section></>}</></Gate>}

export function PublicItemPage(){const{countrySlug='',teamSlug='',collectionSlug,itemSlug=''}=useParams();const x=usePublicData(()=>collectionSlug?api.getItemWithCollection(countrySlug,teamSlug,collectionSlug,itemSlug):api.getItemWithoutCollection(countrySlug,teamSlug,itemSlug),[countrySlug,teamSlug,collectionSlug,itemSlug]);usePageTitle(x.data?.title||'Item');const[active,setActive]=useState(0);useEffect(()=>setActive(0),[itemSlug]);const media=useMemo(()=>x.data?.media?.filter(m=>m.mediaUrl)||[],[x.data]);const selected=media[active]||x.data?.primaryMedia;return <Gate loading={x.loading} error={x.error} empty={!x.data}><>{x.data&&<><PublicBreadcrumbs items={[{label:countrySlug,to:`/site/paises/${countrySlug}`},{label:teamSlug,to:`/site/paises/${countrySlug}/equipes/${teamSlug}`},...(collectionSlug?[{label:collectionSlug,to:`/site/paises/${countrySlug}/equipes/${teamSlug}/collections/${collectionSlug}`}]:[]),{label:x.data.title}]}/><article className="public-item-detail"><div className="public-gallery"><PublicMediaImage media={selected} alt={x.data.title} eager className="public-gallery-main"/>{media.length>1&&<div className="public-gallery-thumbs" aria-label="Galeria de imagens">{media.map((m,i)=><button key={m.mediaKey||i} className={i===active?'active':''} aria-label={`Ver imagem ${i+1}`} aria-pressed={i===active} onClick={()=>setActive(i)}><PublicMediaImage media={m} alt={`${x.data!.title}, imagem ${i+1}`}/></button>)}</div>}</div><div><Header eyebrow={teamSlug} title={x.data.title}/><dl className="public-facts"><div><dt>País / região</dt><dd>{pretty(countrySlug)}</dd></div><div><dt>Equipe</dt><dd>{pretty(teamSlug)}</dd></div>{collectionSlug&&<div><dt>Coleção</dt><dd>{pretty(collectionSlug)}</dd></div>}<div><dt>Imagens</dt><dd>{x.data.imagesCount}</dd></div></dl></div></article></>}</></Gate>}

const resultPath=(x:SearchResult)=>x.type==='country'?`/site/paises/${x.countrySlug}`:x.type==='team'?`/site/paises/${x.countrySlug}/equipes/${x.teamSlug}`:x.type==='collection'?`/site/paises/${x.countrySlug}/equipes/${x.teamSlug}/collections/${x.collectionSlug}`:`/site${x.publicRoute}`
export function PublicSearchPage(){const[params,setParams]=useSearchParams(),initial=params.get('q')||'',[term,setTerm]=useState(initial),[query,setQuery]=useState(initial);usePageTitle(query?`Busca: ${query}`:'Busca');useEffect(()=>{const id=setTimeout(()=>{setQuery(term.trim());setParams(term.trim()?{q:term.trim()}:{},{replace:true})},300);return()=>clearTimeout(id)},[term,setParams]);const x=usePublicData(()=>query?api.search(query):Promise.resolve({items:[],total:0,limit:24,offset:0,hasNext:false}),[query]);return <><Header eyebrow="Pesquisa pública" title="Buscar no acervo"/><label className="public-search-large">O que você procura?<input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="País, equipe, coleção ou item"/></label>{query&&<Gate loading={x.loading} error={x.error} empty={!x.data?.items.length}><div className="public-search-results">{x.data?.items.map((i,n)=><Link key={`${i.type}-${i.title}-${n}`} to={resultPath(i)}><PublicMediaImage media={i.primaryMedia} alt={i.title}/><div><span>{({country:'País / região',team:'Equipe',collection:'Coleção',item:'Item'})[i.type]}</span><h2>{i.title}</h2><p>{i.subtitle}</p></div><b>→</b></Link>)}</div></Gate>}</>}
export function PublicLatestPage(){usePageTitle('Últimas inclusões');const[country,setCountry]=useState(''),countries=usePublicData(()=>api.getCountries(),[]),x=usePublicData(()=>api.latest(country),[country]);return <><Header eyebrow="Novidades do acervo" title="Últimas inclusões" copy="Coleções organizadas pelo período em que foram incluídas no arquivo."/><label className="public-latest-filter">País ou região<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">Todos</option>{countries.data?.items.map(i=><option key={i.slug} value={i.slug}>{pretty(i.name)}</option>)}</select></label><Gate loading={x.loading} error={x.error} empty={!x.data?.items.length}><Grid>{x.data?.items.map(i=><PublicCollectionCard key={`${i.countrySlug}-${i.teamSlug}-${i.slug}`} item={i}/>)}</Grid></Gate></>}
export function PublicNotFoundPage(){usePageTitle('Conteúdo não encontrado');return <div className="public-not-found"><p className="public-kicker">404</p><h1>Conteúdo não encontrado.</h1><p>O endereço pode ter mudado ou não fazer parte deste acervo.</p><Link className="public-cta" to="/site">Voltar ao início</Link></div>}
