import { useState } from 'react'
import { Link } from 'react-router-dom'
import type { PublicCollection,PublicCountry,PublicItem,PublicTeam } from '../types'
import PublicMediaImage from './PublicMediaImage'
import { PublicCountryLogo,PublicTeamLogo } from './PublicIdentityMedia'
import { countryEditorialCovers } from '../config/countryEditorialIdentity'
import { teamDisplayName } from '../utils/teamDisplayName'
import { countryDisplayName } from '../utils/countryDisplayName'
const label=(x:string)=>x.replaceAll('_',' ')
const itemPath=(item:PublicItem)=>`/site${item.publicRoute}`
function PublicCountryEditorialCover({slug,name}:{slug:string;name:string}){const[failed,setFailed]=useState(false),cover=countryEditorialCovers[slug];if(!cover||failed)return <div className="public-country-editorial-fallback" role="img" aria-label={`Capa editorial não disponível: ${name}`}><span>{label(name)}</span></div>;return <div className="public-country-editorial-media"><img src={cover.src} alt={cover.alt} loading="lazy" onError={()=>setFailed(true)}/></div>}
export function PublicCountryCard({item,editorial=false}:{item:PublicCountry;editorial?:boolean}){const displayName=countryDisplayName(item.slug||item.name);return <Link className={`public-card public-country-card${editorial?' public-country-card-editorial':''}`} to={`/site/paises/${item.slug}`}>{editorial?<PublicCountryEditorialCover slug={item.slug} name={displayName}/>:<PublicCountryLogo media={item.logoMedia} name={displayName}/>}<div><h3>{displayName}</h3><p>{item.teamsCount} equipes · {item.itemsCount} itens</p></div></Link>}
export function PublicTeamCard({item,featured=false}:{item:PublicTeam;featured?:boolean}){const displayName=teamDisplayName(item);return <Link className={`public-card public-team-card${featured?' public-team-card-featured':''}`} to={`/site/paises/${item.countrySlug}/equipes/${item.slug}`}><PublicTeamLogo media={item.logoMedia} name={displayName}/><div><p className="public-kicker">{countryDisplayName(item.countrySlug)}</p><h3>{displayName}</h3><p>{item.collectionsCount} coleções · {item.itemsCount} itens</p></div></Link>}
export function PublicCollectionCard({item}:{item:PublicCollection}){return <Link className="public-card" to={`/site/paises/${item.countrySlug}/equipes/${item.teamSlug}/collections/${item.slug}`}><PublicMediaImage media={item.primaryMedia} alt={item.name}/><div><p className="public-kicker">{teamDisplayName(item.teamSlug,item.countrySlug)}</p><h3>Camisas da equipe</h3><p>{item.itemsCount} itens · {item.imagesCount} imagens</p></div></Link>}
export function PublicItemCard({item,variant='default'}:{item:PublicItem;variant?:'default'|'latest'}){return <Link className={`public-card${variant==='latest'?' public-latest-card':''}`} to={itemPath(item)}><PublicMediaImage media={item.primaryMedia} alt={item.title}/><div><p className="public-kicker">{teamDisplayName(item.teamSlug,item.countrySlug)}</p><h3>{item.seasonLabel||item.title}</h3>{item.competition&&<p>{item.competition}</p>}{item.description&&<p className="public-card-description">{item.description}</p>}<p>{item.imagesCount} imagens</p></div></Link>}
